const profile = {
    username : "@Unkox1890",
    age : 13,
    isfollow : false,
    follows :  1890,
    following :  1889,
};

console.log(profile);
















Console = "Avoongers"
// Javascript And Other Languages Have A Fixed System, Like Console Cant Be Printed, But Console With A Capital C Can,
// Since A Capital C Console Is Not Fixed, Also Only These Symbols Can Be Used: _,$
console.log(Console)
console.log("I Will Make Money, That Is My Life Goal")
console.log("While Listening To Phonk And Funk Cuz Why Not lol")
console.log("I Like Abducting Kids")